TRAIN:
  RULE_SYSTEM: 
    USE_RULE_SYSTEM: True
    PURITY_MIN: 0.9

PATH:
  DATA_PATH: 'data/MYDATA/my_data.pkl'

DATA:
  DATASET_NAME: "MYDATA"
  SEGMENT:
    USE_SEGMENT: True
    SEGMENT_OPTION: 2 

MODEL:
  MODALITIES_DIMS: [33, 1, 1, 1]
  MAX_T: 512
  SKELETON:
    SKELETON_NUM_JOINTS: 11
    ROOTIDX: 0
    HEAD_IDX: 4
    LEFT_SHOULDER_IDX: 5
    RIGHT_SHOULDER_IDX: 8
    LEFT_WRIST_IDX: 7
    RIGHT_WRIST_IDX: 10
    NECK_IDX: 3