TRAIN:
  RULE_SYSTEM:
    USE_RULE_SYSTEM: False

PATH:
  DATA_PATH: 'data/TRSPD/trspd_data.pkl'

DATA:
  DATASET_NAME: "TRSPD"
  SEGMENT:
    USE_SEGMENT: False
  
MODEL:
  MODALITIES_DIMS: [51, 1, 1, 1]
  MAX_T: 512
  SKELETON:
    SKELETON_NUM_JOINTS: 17
    ROOTIDX: 0
    HEAD_IDX: 3
    LEFT_SHOULDER_IDX: 4
    RIGHT_SHOULDER_IDX: 8
    LEFT_WRIST_IDX: 6
    RIGHT_WRIST_IDX: 10
    NECK_IDX: 2